version: "3.7"
services:
  zookeeper:
    image: zookeeper:3.5.6
    ports:
      - 2181:2181
    container_name: zookeeper
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    container_name: kafka
